In [12]:
faqs = """What is your name? My name is Chatbot.
How are you? I am fine.
What are you doing? I am chatting with you.
Where do you live? I exist in the cloud.
What is your favorite color? I like blue.
Do you like music? Yes, I do.
What kind of music do you like? I like classical music.
Can you help me? Yes, I can.
What is the weather like today? I am not sure, but you can check online.
What time is it? I do not have a clock, but you can check your device.
How old are you? I am just a program, so I do not age.
What do you eat? I do not eat, but I like data.
Are you a robot? Yes, I am a chatbot.
Can you dance? No, but I can generate dance steps.
Do you sleep? No, I am always active.
Do you watch movies? No, but I can recommend movies.
What is your favorite movie? I do not watch movies, but I have heard about The Matrix.
Do you play games? No, but I can suggest some.
Do you like sports? I do not play, but I can tell you about them.
Who created you? I was created by developers.
What is your purpose? My purpose is to assist and chat with you.
How can I learn programming? You can start with online courses and practice.
Do you have friends? I interact with many users daily.
What languages do you speak? I understand multiple languages, including English.
Can you tell jokes? Yes, I can.
Tell me a joke? Why don’t skeletons fight? Because they do not have the guts.
How do I cook pasta? Boil water, add pasta, and cook until soft.
What is your favorite food? I do not eat, but I know many recipes.
Can you sing? No, but I can provide lyrics.
What do you do for fun? I chat with people.
Can you read books? I can summarize books for you.
Do you have a family? No, but I am part of a system.
How do I learn a new language? Practice daily and use language learning apps.
Can you tell me a story? Yes, I can generate a short story for you.
What is the capital of France? The capital of France is Paris.
What is 2 + 2? The answer is 4.
How can I improve my memory? Practice with memory exercises and repetition.
What is the fastest animal? The peregrine falcon is the fastest.
What is the biggest ocean? The Pacific Ocean is the largest.
How do I stay healthy? Eat well, exercise, and sleep well.
Can you solve math problems? Yes, I can.
Do you know history? Yes, I can provide historical facts.
Can you write poetry? Yes, I can generate poems.
Do you believe in ghosts? I do not have beliefs, but I can tell ghost stories.
How do I fix my computer? Try restarting it first.
Do you know any riddles? Yes, I do.
What is the smallest country? Vatican City is the smallest.
How do I train a pet? Be patient and use rewards.
Can you do magic? No, but I can show you magic tricks.
What is your favorite subject? I like all subjects equally.
How do I bake a cake? Follow a recipe with flour, eggs, and sugar.
Can you tell me my future? No, but I can guess.
What is the speed of light? It is approximately 299,792 km/s.
Can you teach me yoga? I can suggest yoga exercises.
How do I make coffee? Brew hot water with coffee grounds.
Why is the sky blue? Because of the way light scatters in the atmosphere.
How do I start a business? Create a plan and register your company.
What is your opinion on AI? AI is a fascinating technology.
Can you translate languages? Yes, I can translate some phrases.
How do I meditate? Sit quietly and focus on your breath.
What is the meaning of life? That is a deep question.
How do I stay motivated? Set goals and take breaks when needed.
What is the best way to travel? It depends on your destination.
Can you drive? No, I do not have a car.
How do I learn guitar? Start with simple chords and practice daily.
What is the coldest place on Earth? Antarctica is the coldest.
Can you help with homework? Yes, I can explain concepts.
How do I save money? Spend wisely and track your expenses.
What is the best book to read? It depends on your interests.
How do I lose weight? Eat healthily and exercise regularly.
Can you give me a quote? "Believe in yourself and all that you are."
How do I improve my English? Practice speaking and reading daily.
Can you explain quantum physics? Quantum physics is the study of tiny particles.
What is the best way to relax? Listen to music or meditate.
How do I become successful? Work hard and stay consistent.
What is the meaning of AI? AI stands for Artificial Intelligence.
How do I write a resume? List your skills and experience clearly.
What is your favorite animal? I do not have one, but I like all animals.
Can you help with programming? Yes, I can answer coding questions.
How do I become a doctor? Study medicine and complete training.
What is the most spoken language? English and Mandarin are widely spoken.
Can you describe space? Space is vast and full of stars.
How do I cook rice? Boil water, add rice, and let it cook.
What is your favorite sport? I do not play sports.
Can you tell me a fun fact? Bananas are berries, but strawberries are not.
How do I write a book? Start with an idea and outline your story.
What is the best way to learn? Practice and stay curious.
Can you do my homework? No, but I can help explain it.
What is the most important skill? Communication is very important.
How do I be more confident? Believe in yourself and practice speaking.
What is the safest way to travel? Air travel is statistically the safest.
Can you explain gravity? Gravity pulls objects toward each other.
How do I plan a trip? Choose a destination and set a budget.
What is the most popular hobby? Reading is a common hobby.
Can you suggest a TV show? It depends on what you like.
How do I improve focus? Avoid distractions and take short breaks.
What is the tallest building? The Burj Khalifa is the tallest.
How do I keep my mind sharp? Solve puzzles and keep learning.
What is your favorite thing to do? I like chatting with people.
How do I build a chatbot? Learn AI and NLP techniques."""

In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
tokenizer = Tokenizer()

In [13]:
tokenizer.fit_on_texts([faqs])

In [14]:
len(tokenizer.word_index)

373

In [15]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [16]:
input_sequences

[[6, 4],
 [6, 4, 11],
 [6, 4, 11, 62],
 [6, 4, 11, 62, 19],
 [6, 4, 11, 62, 19, 62],
 [6, 4, 11, 62, 19, 62, 4],
 [6, 4, 11, 62, 19, 62, 4, 44],
 [10, 20],
 [10, 20, 3],
 [10, 20, 3, 1],
 [10, 20, 3, 1, 24],
 [10, 20, 3, 1, 24, 139],
 [6, 20],
 [6, 20, 3],
 [6, 20, 3, 140],
 [6, 20, 3, 140, 1],
 [6, 20, 3, 140, 1, 24],
 [6, 20, 3, 140, 1, 24, 63],
 [6, 20, 3, 140, 1, 24, 63, 13],
 [6, 20, 3, 140, 1, 24, 63, 13, 3],
 [141, 2],
 [141, 2, 3],
 [141, 2, 3, 142],
 [141, 2, 3, 142, 1],
 [141, 2, 3, 142, 1, 143],
 [141, 2, 3, 142, 1, 143, 30],
 [141, 2, 3, 142, 1, 143, 30, 7],
 [141, 2, 3, 142, 1, 143, 30, 7, 144],
 [6, 4],
 [6, 4, 11],
 [6, 4, 11, 25],
 [6, 4, 11, 25, 145],
 [6, 4, 11, 25, 145, 1],
 [6, 4, 11, 25, 145, 1, 16],
 [6, 4, 11, 25, 145, 1, 16, 64],
 [2, 3],
 [2, 3, 16],
 [2, 3, 16, 35],
 [2, 3, 16, 35, 15],
 [2, 3, 16, 35, 15, 1],
 [2, 3, 16, 35, 15, 1, 2],
 [6, 146],
 [6, 146, 17],
 [6, 146, 17, 35],
 [6, 146, 17, 35, 2],
 [6, 146, 17, 35, 2, 3],
 [6, 146, 17, 35, 2, 3, 16],
 [6,

In [17]:
max_len = max([len(x) for x in input_sequences])

In [18]:
max_len

17

In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [20]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,   6,   4],
       [  0,   0,   0, ...,   6,   4,  11],
       [  0,   0,   0, ...,   4,  11,  62],
       ...,
       [  0,   0,   0, ...,  32,  34,   9],
       [  0,   0,   0, ...,  34,   9, 372],
       [  0,   0,   0, ...,   9, 372, 373]], dtype=int32)

In [21]:
X = padded_input_sequences[:,:-1]

In [22]:
X

array([[  0,   0,   0, ...,   0,   0,   6],
       [  0,   0,   0, ...,   0,   6,   4],
       [  0,   0,   0, ...,   6,   4,  11],
       ...,
       [  0,   0,   0, ...,  44,  32,  34],
       [  0,   0,   0, ...,  32,  34,   9],
       [  0,   0,   0, ...,  34,   9, 372]], dtype=int32)

In [23]:
y = padded_input_sequences[:,-1]

In [24]:
X.shape

(1029, 16)

In [25]:
y.shape

(1029,)

In [27]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=374)

In [28]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
y.shape

(1029, 374)

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [48]:
model = Sequential()

# Embedding layer (input_length is removed)
model.add(Embedding(input_dim=374, output_dim=100))

# First LSTM layer with return_sequences=True
model.add(LSTM(150, return_sequences=True))

# Second LSTM layer
model.add(LSTM(150))

# Dense output layer with softmax activation
model.add(Dense(374, activation='softmax'))

In [49]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [50]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_12 (LSTM)                       │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_13 (LSTM)                       │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

In [ ]:
import time
text = "what is the fee"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)